name: Lint

on:
  push:
    branches:
      - main

  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  lint:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
